export const PLAN_LIMITS = {
  free: {
    name: "Free",
    price: 0,
    prospectsPerMonth: 50,
    emailsPerMonth: 100,
    campaigns: 1,
    teamMembers: 1,
    templates: 3,
    followupRounds: 1,
    attachments: false,
    customAI: false,
    alertChannels: ["email"],
    apiAccess: false,
    aiResearchDepth: "basic",
  },
  pro: {
    name: "Pro",
    price: 299,
    prospectsPerMonth: 2000,
    emailsPerMonth: 10000,
    campaigns: 20,
    teamMembers: 5,
    templates: Infinity,
    followupRounds: 3,
    attachments: true,
    customAI: true,
    alertChannels: ["email", "feishu", "wecom"],
    apiAccess: true,
    aiResearchDepth: "deep",
  },
  enterprise: {
    name: "Enterprise",
    price: -1,
    prospectsPerMonth: Infinity,
    emailsPerMonth: Infinity,
    campaigns: Infinity,
    teamMembers: Infinity,
    templates: Infinity,
    followupRounds: Infinity,
    attachments: true,
    customAI: true,
    alertChannels: ["email", "feishu", "wecom", "dingtalk", "slack", "webhook"],
    apiAccess: true,
    aiResearchDepth: "deep_custom",
  },
} as const;

export type Plan = keyof typeof PLAN_LIMITS;
